

export const BIKER_REGISTER_REQUEST = 'BIKER_REGISTER_REQUEST';
export const BIKER_REGISTER_SUCCESS = 'BIKER_REGISTER_SUCCESS';
export const BIKER_REGISTER_FAIL = 'BIKER_REGISTER_FAIL';

export const BIKER_LOGIN_REQUEST = 'BIKER_LOGIN_REQUEST';
export const BIKER_LOGIN_SUCCESS = 'BIKER_LOGIN_SUCCESS';
export const BIKER_LOGIN_FAIL = 'BIKER_LOGIN_FAIL';

export const BIKER_PROFILE_REQUEST = 'BIKER_PROFILE_REQUEST';
export const BIKER_PROFILE_SUCCESS = 'BIKER_PROFILE_SUCCESS';
export const BIKER_PROFILE_FAIL = 'BIKER_PROFILE_FAIL';


export const BIKER_LOGOUT_REQUEST = 'BIKER_LOGOUT_REQUEST';
export const BIKER_LOGOUT_SUCCESS = 'BIKER_LOGOUT_SUCCESS';