export const GET_PARCELS_REQUEST = 'GET_PARCELS_REQUEST';
export const GET_PARCELS_SUCCESS = 'GET_PARCELS_SUCCESS';
export const GET_PARCELS_FAIL = 'GET_PARCELS_FAIL';


export const PICK_PARCEL_REQUEST = 'PICK_PARCEL_REQUEST';
export const PICK_PARCEL_SUCCESS = 'PICK_PARCEL_SUCCESS';
export const PICK_PARCEL_FAIL = 'PICK_PARCEL_FAIL';