

export const SENDER_REGISTER_REQUEST = 'SENDER_REGISTER_REQUEST';
export const SENDER_REGISTER_SUCCESS = 'SENDER_REGISTER_SUCCESS';
export const SENDER_REGISTER_FAIL = 'SENDER_REGISTER_FAIL';

export const SENDER_LOGIN_REQUEST = 'SENDER_LOGIN_REQUEST';
export const SENDER_LOGIN_SUCCESS = 'SENDER_LOGIN_SUCCESS';
export const SENDER_LOGIN_FAIL = 'SENDER_LOGIN_FAIL';

export const SENDER_PROFILE_REQUEST = 'SENDER_PROFILE_REQUEST';
export const SENDER_PROFILE_SUCCESS = 'SENDER_PROFILE_SUCCESS';
export const SENDER_PROFILE_FAIL = 'SENDER_PROFILE_FAIL';

export const SENDER_LOGOUT_REQUEST = 'SENDER_LOGOUT_REQUEST';
export const SENDER_LOGOUT_SUCCESS = 'SENDER_LOGOUT_SUCCESS';